/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/3DModel/3D_PortofolioModel.glb --transform 
Files: public/3DModel/3D_PortofolioModel.glb [1.32KB] > C:\Users\OrmatoriFix\Desktop\PortofolioV3\3D_PortofolioModel-transformed.glb [1.1KB] (17%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Model({ customColor, ...props }) {
  const { nodes, materials } = useGLTF(
    "./3DModel/3D_PortofolioModel-transformed.glb",
  );
  return (
    <group {...props} dispose={null}>
      {" "}
      //...props contient tt les element comme rotation, position etc
      <mesh
        geometry={nodes.Cube.geometry}
        material={materials.MainColor}
        material-color={customColor}
      />
    </group>
  );
}

useGLTF.preload("./3DModel/3D_PortofolioModel-transformed.glb");
