/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/3DModel/Reactor.glb --transform 
Files: public/3DModel/Reactor.glb [685.11KB] > C:\Users\OrmatoriFix\Desktop\PortofolioV3\Reactor-transformed.glb [315KB] (54%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function ReactorModel(props) {
  const { nodes, materials } = useGLTF("./3DModel/Reactor-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Cylinder019.geometry}
        material={materials.PaletteMaterial002}
      />
      <mesh
        geometry={nodes.Cylinder019_1.geometry}
        material={materials.PaletteMaterial003}
      />
      <mesh
        geometry={nodes.Cylinder019_2.geometry}
        material={materials.PaletteMaterial001}
      />
    </group>
  );
}

useGLTF.preload("./3DModel/Reactor-transformed.glb");
